apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: backend-user
  name: backend-user
spec: 
  replicas: 2
  selector: 
    matchLabels: 
      app: backend-user
  template: 
    metadata: 
      labels: 
        app: backend-user
    spec: 
      restartPolicy: Always
      containers: 
        - image: kulturman/udagram-api-user:v3
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "500m"
          name: backend-user
          ports: 
            - 
              containerPort: 8080
          env:
            - name: AWS_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: api-config
                  key: bucket
            - name: AWS_REGION
              valueFrom:
                configMapKeyRef:
                  name: api-config
                  key: region
            - name: AWS_PROFILE
              valueFrom:
                configMapKeyRef:
                  name: api-config
                  key: profile
            
            #Secrets
            - name: POSTGRES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: api-secret
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: api-secret
                  key: password
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: api-secret
                  key: host
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: api-secret
                  key: db
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: api-secret
                  key: jwt-secret