apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: reverse-proxy
  name: reverse-proxy
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: reverse-proxy
  template: 
    metadata: 
      labels: 
        app: reverse-proxy
    spec: 
      containers: 
        - image: kulturman/udagram-reverse-proxy:v3
          name: reverse-proxy
          ports: 
            - 
              containerPort: 8080
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "500m"   
      restartPolicy: Always